import { Poppins, Rajdhani } from "next/font/google";
import "../globals.css";
import "animate.css";

// import Navigation from "../components/Navigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Customize as needed
  variable: "--font-poppins",
});
const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-rajdhani",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${rajdhani.variable}`}>
      <body className="font-poppins overflow-auto">{children}</body>
    </html>
  );
}
